chore: fix workflow for pwn request

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -27,7 +27,7 @@ on:
       - "!*"
     paths-ignore:
       - "**.md"
-  pull_request_target:
+  pull_request:
     types:
       - opened
       - reopened
@@ -39,16 +39,29 @@ jobs:
   setup:
     name: ⚙️ Setup
     runs-on: ubuntu-latest
+    permissions: {} # No permissions needed for setup job
     outputs:
       unityVersions: ${{ steps.setup.outputs.unityVersions }}
     steps:
+      - name: 🔑 Secrets check
+        run: |
+          if [ -z "$UNITY_EMAIL" ] || [ -z "$UNITY_PASSWORD" ] || [ -z "UNITY_LICENSE" ]; then
+            echo "Error: UNITY_EMAIL, UNITY_PASSWORD, and UNITY_LICENSE secrets must be set." | tee -a $GITHUB_STEP_SUMMARY >&2
+            echo "Error: See https://game.ci/docs/github/test-runner#basic-setup" | tee -a $GITHUB_STEP_SUMMARY >&2
+            echo "Error: Set the secrets at ${{ github.server_url }}/${{ github.repository }}/settings/secrets/actions" | tee -a $GITHUB_STEP_SUMMARY >&2
+            exit 1
+          fi
+        env:
+          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
+          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
+          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
       - name: ⚙️ Find target Unity versions
         id: setup
         run: |
           echo "==== Target Unity Versions ===="
-          LATEST_VERSIONS=`npx unity-changeset@latest list --versions --latest-patch --min ${MINIMUM_VERSION} --json --all --ignore-alpha`
+          LATEST_VERSIONS=`npx -y unity-changeset@latest list --json --versions --all --latest-patch --ignore-alpha --min ${MINIMUM_VERSION}`
           if [ "${{ inputs.usePeriodVersions }}" = "true" ]; then
-            ADDITIONAL_VERSIONS=`npx unity-changeset list --versions --grep '0f' --min ${MINIMUM_VERSION} --json --ignore-alpha`
+            ADDITIONAL_VERSIONS=`npx -y unity-changeset@latest list --json --versions --ignore-alpha --min ${MINIMUM_VERSION} --grep '0f'`
           else
             ADDITIONAL_VERSIONS=[]
           fi
@@ -66,28 +79,12 @@ jobs:
     needs: setup
     strategy:
       fail-fast: false
-      max-parallel: 6
+      max-parallel: 8
       matrix:
         unityVersion: ${{ fromJson(needs.setup.outputs.unityVersions) }}
     steps:
       - name: 🚚 Checkout ($${{ github.ref }})
-        if: github.event_name == 'push'
         uses: actions/checkout@v6
-
-      - name: 🚚 Checkout pull request (pull_request_target)
-        if: github.event_name == 'pull_request_target'
-        uses: actions/checkout@v6
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          fetch-depth: 0
-
-      - name: 🚚 Marge pull request (pull_request_target)
-        if: github.event_name == 'pull_request_target'
-        run: |
-          git config user.name "GitHub Actions"
-          git config user.email "actions@github.com"
-          git rebase ${{ github.event.pull_request.base.sha }}
-          git log --oneline -n 10
 
       - name: 📥 Cache library
         uses: actions/cache@v5
